application: appname
version: 1
runtime: python27
api_version: 1
threadsafe: true


builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: MySQLdb
  version: 1.2.4
- name: ssl
  version: latest
- name: pycrypto
  version: "2.6"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: app/static/img/favicon.ico
  upload: app/static/img/favicon.ico

- url: /robots.txt
  static_files: app/static/robots.txt
  upload: app/static/robots.txt

- url: /static
  static_dir: app/static

- url: .*
  script: run.app.app